a = input()
var = a.split()
print(int(var[0]) + int(var[1]))
print(int(var[0]) - int(var[1]))
print(int(var[0]) * int(var[1]))
print(int(int(var[0]) / int(var[1])))
print(int(var[0]) % int(var[1]))